### PR TITLE
Changed autoloader handling, minor tweaks to unstick Travis.

### PR DESCRIPTION
**Pull request by simensen**
With this change bootstrapping the project for testing only requires `composer install` to be run. This will setup Composer's autoloader (`vendor/autoload.php`) in such a way that Ferrit will be able to run tests.
- Removed the Git submodule
- Added additional files to .gitignore (`vendor/` and `build/`)
- Skip the `MIMEDetector` test if `MIME_Type` is not available
- Instruct Travis to run Composer
- Instruct Travis to test PHP 5.3.3 in addition to PHP 5.3 (latest stable)

---

One of the big things I'd like to move toward is **away** from `MIME_Type` entirely. I think a combination of some other projects would help us get away from this dependency.

This is going to require a lot of work with Composer. How comfortable are you with this projecting having external dependencies managed via Composer instead of Git submodules?

Let me know your thoughts on that direction. :)

Thanks!

### CODE REVIEW

**Comment by simensen** [comment]
@haswalt Please let me know if you like where I'm wanting to go with this. :)

I figure this is a good first test to see whether or not my goals are in line with the goals of Ferret as it stands now. If not that is ok, but I'd like to find out sooner rather than later.

Also, how do you feel about PSR-1 and PSR-2?

**Comment by simensen** [comment]
Updated per request from @haswalt to not include the test skip.

This particular build will no longer pass Travis because it will fail on account of the missing MIME Type dependency.

**Comment by haswalt** [comment]
Can you rebase this one then I'll merge

**Comment by simensen** [comment]
Rebased.

**Pull request merged**
